### ISSUE TITLE
Which public Microsoft/Skype APIs can we use to create meeting urls?

### ISSUE THREAD

**Issue by maciej-zywno** [OfficeDev/skype-ios-app-sdk-samples#9] opened 2016-05-12 15:00 UTC
I'm aware that it is outside of the app-sdk-samples scope. However, we, as a startup that has no corporate wide MS/Office/Skype/UCWA servers, are lost on what API endpoints we should use to create meeting urls that are to be further passed to our iOS app. Our goal is to embed Skype video chats in our iOS app.

According to this diagram [https://msdn.microsoft.com/en-us/skype/appsdk/embedskypeb2ccomms](https://msdn.microsoft.com/en-us/skype/appsdk/embedskypeb2ccomms) we should be sending requests to `Skype Platform` from our own own backend. What is a `Skype Platform` endpoint to create meetings. We do not have our own Skype for Business server so I'm assuming that should be a public endpoint.

Should we start by be following `Skype Web SDK` [documentation](https://msdn.microsoft.com/en-us/library/office/mt622687%28v=office.16%29.aspx) and creating a `WEB APPLICATION AND/OR WEB API` app or a `NATIVE CLIENT APPLICATION` app? 

Could anyone point to the step-by-step documentation how to integrate one's own backend with an appropriate cloud hosted `Skype Platform` API to create meetings?

**Comment by richardtaylorrt** [comment] 2016-05-12 22:11
Hi - if you don't have your own Skype for Business server, you need a Skype for Business Online subscription (as part of Office 365).  If you don't already have one, you can get a developer subscription [here](
http://dev.office.com/devprogram). 

Once you have a licensed Skype for Business user, you can use this account to:
- create a [meeting manually for test purposes](https://msdn.microsoft.com/en-us/skype/appsdk/getmeetingurl)
- create a meeting programmatically via the Skype for Business [User API (UCWA)](https://msdn.microsoft.com/en-us/library/office/dn324971(v=office.16).aspx).   See this [stackoverflow answer](http://stackoverflow.com/questions/30628693/programatically-schedule-create-skype-for-business-meeting) for more about how to do this.

Note that there must be a licensed Skype for Business user as one of the participants in all meetings that are joined by "guests" using the App SDK.

Please let us know how you get on.

**Comment by zywy** [comment] 2016-05-12 23:37
Thank you. I wanted to continue the conversation at StackOverflow however I am not yet able to that (don't have enough Stack "points") so I'll do it here.

How/Where do you get ```AAEB...buHc``` value you use in the request below from?

```
POST https://lyncweb.contoso.com/ucwa/oauth/v1/applications/103...740/onlineMeetings/myOnlineMeetings HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer cwt=AAEB...buHc
```

Also, we are not sure what kind of WindowsAzure app (```WEB APPLICATION AND/OR WEB API``` or ```NATIVE CLIENT APPLICATION``` type?) we need for our scenario which is: we want to create meetings programmatically from our backend with no end-user interactions needed.

**Comment by zywy** [comment] 2016-05-13 08:02
Also, should we send POST requests to  ```contoso.com``` or is it a fake domain?

**Comment by zywy** [comment] 2016-05-13 12:28
We made a little progress. We're stuck at ```https://webdir1e.online.lync.com/WebTicket/oauthtoken``` request and it seems that it's quite a common issues developers tend to have when dealing with UCWA.

Could you write what ```grant_type``` (```urn:microsoft.rtc:passive```, ```password``` ?) we should use and whether we should fill ```username``` and ```password``` params when sending requests fully programmatically from our backend? 

* So far we have got a ```redirect href``` from a response (we sent a request to ```http://lyncdiscover.razorbear.com/``` with "lyncdiscover" configured in our DNS). 
* Then when using GET user from ```https://webdir1e.online.lync.com/Autodiscover/AutodiscoverService.svc/root/oauth/user?originalDomain=razorbear.com``` gives us ```401``` (which is as far as we know an expected behavior) and headers that include ```WWW-Authenticate →Bearer trusted_issuers="(...)-000000000000@*", client_id="(...)-000000000000", authorization_uri="https://login.windows.net/common/oauth2/authorize", MsRtcOAuth href="https://webdir1e.online.lync.com/WebTicket/oauthtoken",grant_type="urn:microsoft.rtc:passive,urn:microsoft.rtc:anonmeeting"``` 
* And then we're stuck with ```https://webdir1e.online.lync.com/WebTicket/oauthtoken``` request which either returns ```unsupported_grant_type``` with ```X-Ms-diagnostics (...) reason="No valid security token."``` or ```401 - Unauthorized: Access is denied due to invalid credentials.``` with ```X-Ms-diagnostics (...) "The user is not signed in with WS Federation Passive credentials."``` depending on whether we use ```urn:microsoft.rtc:passive,urn:microsoft.rtc:anonmeeting``` or ```password``` as ```grant_type``` parameter.

Thank you for any help.

**Comment by richardtaylorrt** [comment] 2016-05-13 18:14
Hi - are you following the [instructions to access UCWA for Skype for Business Online](https://msdn.microsoft.com/EN-US/library/office/mt590890(v=office.16).aspx)?.  In particular, take a look at the process to [register](https://msdn.microsoft.com/en-us/library/office/mt592709(v=office.16).aspx) and then [authenticate](https://msdn.microsoft.com/en-us/library/office/mt590891(v=office.16).aspx) your app.

Some specific answers to your questions:
- You need to register your application as a 'Web Application and/or Web API'
- You need to start off with a GET to https://webdir.online.lync.com/autodiscover/autodiscoverservice.svc/root .  I'm not sure if using your own 'razorbear' discover endpoint will work.
- You need to configure your app for the 'implicit grant' flow and then use this to request an access token.  Full details in the links above.  Right now, I think this means you have to get the user to 'consent' to give access to your app.  I understand that you want to do this purely programmatically without user intervention.  This isn't supported yet, but it's coming: I'll let you know if I find out more details.
- If you follow this flow, you shouldn't be redirected to the 'webTicket' URI you are stuck on.  Web tickets aren't used for API/SDK based applications.

There is also a [video](https://channel9.msdn.com/Events/Build/2016/T629) that covers some of the initial steps.  The relevant bits start at about 09:30.

Please let me know if this helps move you forward.

**Comment by MatUrbanski** [comment] 2016-05-17 06:46
I'm working together with @zywy on this. I was able to use https://github.com/OfficeDev/skype-web-sdk-samples/tree/master/SkypeWebSDKOnlineSample to receive access token. I sign in in to Microsoft and I was redirected to my app url with the following parameters:

```
https://my_app/users/sign_in#access_token=ey..qw&token_type=Bearer&expires_in=3599&session_state=c77..61
```

Now I'm trying to send GET request to 
```
https://webdir1e.online.lync.com/Autodiscover/AutodiscoverService.svc/root/oauth/user?originalDomain=razorbear.com
```

with that token. But I've recieved ```500``` http status code with:
``` X-Ms-diagnostics →28032;source="AM41E00EDG02.infra.lync.com";reason="The web ticket is invalid."```

**Comment by zywy** [comment] 2016-05-17 15:38
@richardtaylorrt Hello, we followed the section in [authenticate instructions](https://msdn.microsoft.com/en-us/library/office/mt590891(v=office.16).aspx):

**Sign-in section**

 As explained in "Sign-in" section we sent a request to:

 ```GET  https://login.microsoftonline.com/oauth2/authorize?response_type=token&client_id=aeadda0b-4350-4668-a457-359c60427122&redirect_uri=https%3A%2F%2Flocalhost%3A44326%2F HTTP/1.1```

with:

 ```client_id``` replaced with our Azure webapp ```CLIENT ID```
```redirect_uri``` replaced with the address where our webapp is hosted.


As a response we were redirected to our webapp but the params includes an error message ```Resource identifier is not provided``` and ```error=invalid_resource&error_description=AADSTS50001```.


Our first question is: Is it that a ```resource identifier``` is indeed missing or is it rather an issue with our Azure application configuration? 


We went to by adding:

* resource param ```https://webdir1e.online.lync.com/``` 
* prompt param ```consent```

to ```GET  https://login.microsoftonline.com/oauth2/authorize?response_type=token&client_id=aeadda0b-4350-4668-a457-359c60427122&redirect_uri=https%3A%2F%2Flocalhost%3A44326%2F HTTP/1.1``` request and then received:

* ```access_token``` of type ```Bearer```.
* ```session_state```

We disregarded received params and moved on to Autodiscovery section in the documentation.

**Autodiscovery section**

We followed Autodiscovery section and received ```authorization URI``` to be used in the next section.

**Requesting an access token using implicit grant flow section**

We sent an HTTP GET request to ```authorization URI``` and received ```id_token``` only. No ```access_token``` and ```refresh_token``` were there in the response. 

Any ideas on what we might be doing wrong?

**Comment by richardtaylorrt** [comment] 2016-05-18 00:00
Hi folks - sorry you're having difficulty with this.

I think the instructions may be a bit misleading and I'm going to get an expert to double-check them and get back to you.  

In the meantime, please could you also send a network capture (using F12 browser tools) of your failing HTTPS flows to the 'Skype developer insiders' email address that is on this [page](https://msdn.microsoft.com/en-us/skype/appsdk/feedback) under 'API bugs'.

[One quick idea I haven't tested: use the access token you received (don't disregard it).  Try skipping ahead to the section about 'Resending an autodiscovery request with the bearer token' using this access token.]

**Comment by richardtaylorrt** [comment] 2016-05-24 23:08
Hi - the expert for this is currently out on vacation.  He should respond next week when he's back.  In the meantime, please try the following and let us know if it helps:

1. Start again with the instructions [here](https://msdn.microsoft.com/en-us/library/office/mt590891(v=office.16).aspx), with the following changes.
2. Ignore the 'Sign In' section completely.
3. During the 'Requesting an access token using implicit grant flow' section, request a 'response_type' of 'token' not 'id_token'.
4. You should get redirected back to your app.  Retrieve the requested (access) token from the # fragment parameters.  https://yourapp#access_token=abc...
5. Use this token in the 'Resending an autodiscovery request with the bearer token' section.
6. Try using this token in the 'Access the applications resource' section too.  If it doesn't work, request a different access token in the same way as step #2.  Except that the 'resource' parameter in this request should now be the applications resource URI you are trying to hit.

If this doesn't work then (as per earlier reply above) please do email us and send us a network capture of the failed attempt(s).  Thanks.

**Comment by andrei-markeev** [comment] 2016-11-20 16:42
I'm afraid the [official documentation](https://msdn.microsoft.com/skype/ucwa/AuthenticationUsingAzureAD) is incomplete and partially incorrect. Took me about 3 days to figure out the correct flow. Even had to peek into how O365 Outlook Web Access does that, and only after that was able to produce the correct sequence.

The steps are as follows:

1. Prepare Azure AD Application: setup at least implicit flow and redirect URL.
2. Root autodiscovery server is https://webdir.online.lync.com
3. Authenticate against https://login.microsoftonline.com/common/oauth2/authorize to access the autodiscovery server. The correct response_type parameter is **token** (not **id_token** as in official documentation).
4. Parse out **access_code** from URL hash (hash is only accessible on the client of course)
5. Issue request to /autodiscover/autodiscoverservice.svc/root
6. If response contains **redirect** node, then this will be next autodiscovery server, so _LOOP to step 2_.
7. If response does not contain **redirect**, it should contain **applications** url
8. Again authenticate with https://login.microsoftonline.com/common/oauth2/authorize to access server where applications url points
9. Parse out access_code
10. Finally use applications URL to create app and continue further using the API

In desktop web applications, you'll also get problems on step 4 because of CORS - so will need to do request from server or use XFrame thing, but luckily this shouldn't apply to mobile applications.

And of course if you do a very small mistake on some step, the whole workflow will not work. Welcome to Skype for Business :D

Steps 7-9 should be executed again every time the token expires (in this case you'll get 401).

**Comment by jovillas** [comment] 2017-09-07 22:27
Thanks for the summary.

I'm closing this ticket since the last comment answer the question. Please keep referring to this issue as reference.

**Closed by jovillas** 2017-09-07 22:27 UTC
